//将数据展现到页面
export const DONE_TOP_MOVIE='DONE_TOP_MOVIE';
export const TOGGLE_TOP_MOVIE='TOGGLE_TOP_MOVIE';
export const DONE_USA_MOVIE='DONE_USA_MOVIE';
export const TOGGLE_USA_MOVIE='TOGGLE_USA_MOVIE';
//获取json数据
export const FEACH_TOP_MOVIE='FEACH_TOP_MOVIE';
export const FEACH_USA_MOVIE='FEACH_USA_MOVIE';
//loading的改变
export const DONE_LOADING='DONE_LOADING';
//电影的详细内容
export const FEACH_MOVIE_DETAIL='FEACH_MOVIE_DETAIL';
export const TOGGLE_MOVIE_DETAIL='TOGGLE_MOVIE_DETAIL';
export const DONE_MOVIE_DETAIL='DONE_MOVIE_DETAIL';
//搜索
export const FEACH_SEARCH_MOVIE='FEACH_SEARCH_MOVIE';
export const TOGGLE_SEARCH_MOVIE='TOGGLE_SEARCH_MOVIE';
export const DONE_SEARCH_MOVIE='DONE_SEARCH_MOVIE';
